# Generated by Django 4.2.1 on 2023-06-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_alter_reserva_data_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data',
        ),
    ]
