# Generated by Django 4.2.1 on 2023-06-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_reserva_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_agendamento',
            field=models.DateField(default=None, help_text='dd/mm/aaaa', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.CharField(default=None, max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome',
            field=models.CharField(default=None, max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_pet',
            field=models.CharField(default=None, max_length=50, verbose_name='Nome do Pet:'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(default=None, max_length=11, verbose_name='Telefone'),
        ),
    ]
