# Generated by Django 4.2.1 on 2023-06-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_alter_reserva_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_agendamento',
            field=models.DateField(default=None, help_text='dd/mm/aaaa', verbose_name='Data'),
        ),
    ]
