# Generated by Django 4.2.3 on 2023-07-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_petshop_reserva_petshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raça', models.CharField(max_length=50, verbose_name='Raça')),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='petshop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserva.petshop'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserva.categoria'),
        ),
    ]
