# Generated by Django 4.2.1 on 2023-07-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_categoria_alter_reserva_petshop_reserva_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_agendamento',
            field=models.DateField(blank=True, default=None, help_text='dd/mm/aaaa', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.CharField(blank=True, choices=[('Indiferente', 'Indiferente'), ('Manhã', 'Manhã'), ('Tarde', 'Tarde')], default='Indiferente', max_length=30, verbose_name='Horário:'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='levaetraz',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default=None, max_length=3, verbose_name='Precisa de Transtorte? '),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_pet',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Nome do Pet:'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('Pequeno', 'Pequeno'), ('Pequeno', 'Medio'), ('Grande', 'Grande')], default=None, max_length=10, verbose_name='Tamanho: '),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(blank=True, default=None, max_length=11, verbose_name='Telefone'),
        ),
    ]
