# Generated by Django 4.2.1 on 2023-07-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0011_alter_reserva_data_agendamento_alter_reserva_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
